netgusto_demo:
    resource: "@NetgustoDemoBundle/Resources/config/routing.yml"
    prefix:   /

netgusto_baikal_admin:
    resource: "@NetgustoBaikalAdminBundle/Resources/config/routing.yml"
    prefix:   /admin