netgusto_demo:
    resource: "@NetgustoDemoBundle/Resources/config/routing.yml"
    prefix:   /

netgusto_admin:
    resource: "@NetgustoAdminLTEBundle/Resources/config/routing.yml"
    prefix:   /admin