parameters:
#    netgusto_baikal_core.example.class: Netgusto\Baikal\CoreBundle\Example

services:
#    netgusto_baikal_core.example:
#        class: %netgusto_baikal_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
