netgusto_demo_homepage:
    pattern:  /
    defaults: { _controller: NetgustoDemoBundle:Front:index }

netgusto_demo_admin:
    resource: @NetgustoAdminLTEBundle/Resources/config/routing.yml
    prefix:  /admin
