netgusto_empty_homepage:
    pattern:  /
    defaults: { _controller: NetgustoEmptyBundle:Default:index }

netgusto_empty_subpage:
    pattern:  /subpage
    defaults: { _controller: NetgustoEmptyBundle:Default:index }