<?php

namespace Netgusto\Baikal\DavServicesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressbookContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressbookContactRepository extends EntityRepository {

    public function countAll() {
        $qb = $this->createQueryBuilder('AddressbookContact');
        $qb->select('count(AddressbookContact.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
