<?php

namespace Netgusto\Baikal\DavServicesBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Netgusto\Baikal\DavServicesBundle\Entity\User;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
    public function countAll() {
        $qb = $this->createQueryBuilder('Calendar');
        $qb->select('count(Calendar.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findByUser(User $user) {
        $identityprincipal = $user->getIdentityPrincipal();
        
        if(!is_null($identityprincipal)) {
            return $this->findByPrincipaluri($identityprincipal->getUri());
        }

        return array();
    }
}
